version: '{build}'
image:
  - Visual Studio 2013
  - Visual Studio 2017
  - Visual Studio 2019

platform:
  - Win32
  - x64

cache:
  - C:\tmp\VST3 SDK

install:
  - ps: |
      if (-Not (Test-Path "C:\tmp\VST3 SDK")) {
        Invoke-WebRequest "https://web.archive.org/web/20200502121517/https://www.steinberg.net/sdk_downloads/vstsdk366_27_06_2016_build_61.zip" -OutFile "vstsdk.zip"
        Expand-Archive "vstsdk.zip" "C:\tmp"
      }
      if (-Not (Test-Path "C:\tmp\Monad.FLParser.dll")) {
        Invoke-WebRequest "https://github.com/LeStahL/FLParser/releases/download/compatibility-20.9/Monad.FLParser.dll" -OutFile "C:\tmp\Monad.FLParser.dll"
      }

build_script:
  # build native code/tests
  - mkdir build
  - cd build
  - cmake -DCMAKE_GENERATOR_PLATFORM=%PLATFORM% -DVSTSDK3_DIR="C:/tmp/VST3 SDK" -DMONAD_FL_PARSER_DIR="C:/tmp/" ..
  - msbuild /v:minimal /nologo WaveSabre.sln
  - msbuild /v:minimal /nologo /property:Configuration="MinSizeRel" WaveSabre.sln
  - cd ..

test_script:
  - cd build
  - Tests\WaveSabreConvertTests\Debug\WaveSabreConvertTests.exe
  - cd ..
